
// // v2.4NavBarIssue/app/layout.tsx
// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Pacifico } from "next/font/google";
// import "./globals.css";
// import Footer from "../components/Footer";
// import { CartProvider } from "../lib/cartUtils";
// import TopBannerSlider from "../components/TopBannerSlider"; // Re-import TopBannerSlider
// import ConditionalHeader from "../components/ConditionalHeader"; // Import ConditionalHeader

// const pacifico = Pacifico({
//   weight: '400',
//   subsets: ['latin'],
//   display: 'swap',
//   variable: '--font-pacifico',
// })

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Readdy Site",
//   description: "Generated by Readdy",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning={true}>
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
//       >
//         <CartProvider>
//           <TopBannerSlider /> {/* Render TopBannerSlider always */}
//           <ConditionalHeader /> {/* Conditionally render Header for non-homepage */}
//           {/* Removed padding-top from main, as Header will either be managed by ConditionalHeader
//               or directly in page.tsx for homepage */}
//           <main className="min-h-screen"> 
//             {children}
//           </main>
//           <Footer />
//         </CartProvider>
//       </body>
//     </html>
//   );
// }
// enezzae/app/layout.tsx
'use client'; // Mark as a client component to use hooks like usePathname

import { Geist, Geist_Mono, Pacifico } from "next/font/google";
import "./globals.css";
import Footer from "../components/Footer";
import { CartProvider } from "../lib/cartUtils";
import TopBannerSlider from "../components/TopBannerSlider";
import ConditionalHeader from "../components/ConditionalHeader";
import { usePathname } from 'next/navigation'; // Import usePathname

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// REMOVED: export const metadata from here
// export const metadata: Metadata = {
//   title: "Readdy Site",
//   description: "Generated by Readdy",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isAdminPage = pathname === '/admin';

  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} antialiased`}
      >
        <CartProvider>
          {!isAdminPage && <TopBannerSlider />} {/* Hide TopBannerSlider on admin page */}
          {!isAdminPage && <ConditionalHeader />} {/* Hide ConditionalHeader (and thus Header) on admin page */}
          <main className="min-h-screen">
            {children}
          </main>
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}